source $HOME/.config/nvim/keys/mapping.vim
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/theme/airline.vim
source $HOME/.config/nvim/theme/dracula.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/vim-plug/coc.vim
source $HOME/.config/nvim/vim-plug/prettier.vim
source $HOME/.config/nvim/vim-plug/rainbow.vim
source $HOME/.config/nvim/vim-plug/sneak.vim
source $HOME/.config/nvim/vim-plug/tagbar.vim
